# Generated by Django 2.0.2 on 2018-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
