# Generated by Django 2.0.2 on 2018-04-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformfile',
            name='variables',
            field=models.ManyToManyField(blank=True, to='common.Variable'),
        ),
    ]
