# Generated by Django 2.0.2 on 2018-05-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_terraformfile_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformfile',
            name='provider',
            field=models.ForeignKey(on_delete=False, to='common.Provider'),
        ),
    ]
